name: Linux Build

on:
  push:
    branches: 
        - main
        - feature/* 
        - features/* 
        - develop
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: update submodules
      run: git submodule update --init --recursive --remote
    - name: create build folder
      run: mkdir build
      working-directory: sfcomposer
    - name: configure
      run: cmake -DCMAKE_BUILD_TYPE=Release ..
      working-directory: sfcomposer/build
    - name: build
      run: cmake --build .
      working-directory: sfcomposer/build
